mealplans/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from mealplans.views import (
    MealplanCreateView,
    MealplanDeleteView,
    MealplanUpdateView,
    MealplanDetailView,
    MealplanListView,
)


urlpatterns = [
    path("", MealplanListView.as_view(), name="mealplans_list"),
    path("<int:pk>/", MealplanDetailView.as_view(), name="mealplan_detail"),
    path(
        "<int:pk>/delete/", MealplanDeleteView.as_view(), name="mealplan_delete"
    ),
    path("create/", MealplanCreateView.as_view(), name="mealplan_new"),
    path("<int:pk>edit/", MealplanUpdateView.as_view(), name="mealplan_edit"),
    path("accounts/login/", auth_views.LoginView.as_view(), name="login"),
    path("accounts/logout/", auth_views.LogoutView.as_view(), name="logout"),
]

scrumptious/urls.py
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic.base import RedirectView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("recipes/", include("recipes.urls")),
    path("tags/", include("tags.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("recipes_list")),
        name="home",
    ),
    path("accounts/login/", auth_views.LoginView.as_view(), name="login"),
    path("accounts/logout/", auth_views.LogoutView.as_view(), name="logout"),
]

tags/urls.py
from django.urls import path

from tags.views import show_tags

urlpatterns = [
    path("", show_tags, name="tags_list"),
]

mealplans/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.conf import settings


USER_MODEL = settings.AUTH_USER_MODEL
# Create your models here.
class Mealplan(models.Model):
    name = models.CharField(max_length=120)
    date = models.DateField()
    owner = models.ForeignKey(
        USER_MODEL,
        related_name="mealplans",
        on_delete=models.CASCADE,
        null=True,
    )
    recipes = models.ManyToManyField("recipes.Recipe", related_name="mealplans")

mealplans/views.py
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView

from django.contrib.auth.mixins import LoginRequiredMixin

from mealplans.models import Mealplan

# Create your views here.


class MealplanListView(LoginRequiredMixin, ListView):
    model = Mealplan
    template_name = "mealplans/list.html"
    paginate_by = 3

    def get_queryset(self):
        return Mealplan.objects.filter(owner=self.request.user)


class MealplanDetailView(DetailView):
    model = Mealplan
    template_name = "mealplans/detail.html"

    def get_queryset(self):
        return Mealplan.objects.filter(owner=self.request.user)


class MealplanCreateView(LoginRequiredMixin, CreateView):
    model = Mealplan
    template_name = "mealplans/new.html"
    fields = ["name", "date", "recipes"]
    success_url = reverse_lazy("mealplans_list")

    def form_valid(self, form):
        plan = form.save(commit=False)
        plan.owner = self.request.user
        plan.save()
        form.save_m2m()
        return redirect("mealplan_detail", pk=plan.id)


class MealplanUpdateView(LoginRequiredMixin, UpdateView):
    model = Mealplan
    template_name = "mealplans/edit.html"
    fields = ["name", "date", "recipes"]

    def get_queryset(self):
        return Mealplan.objects.filter(owner=self.request.user)

    def get_success_url(self) -> str:
        return reverse_lazy("mealplan_detail", args=[self.object.id])


class MealplanDeleteView(LoginRequiredMixin, DeleteView):
    model = Mealplan
    template_name = "mealplans/delete.html"
    success_url = reverse_lazy("mealplans_list")

    def get_queryset(self):
        return Mealplan.objects.filter(owner=self.request.user)

mealplans/templates/mealplans/delete.html
{% extends 'base.html' %}

{% block content %}
    <main>
        <form method="post">
            {% csrf_token %}
            <p>Are you sure you want to delete "{{ mealplan }}"?</p>
            {{ form.as_p }}
            <div class="control">
                <button class="button">Delete</button>
            </div>
        </form>
    </main>
{% endblock content %}

mealplans/templates/mealplans/detail.html
{% extends 'base.html' %}

{% load markdownify %}

{% block content %}
  <main class="recipe-detail">
    <div>
      <a href="{% url 'mealplan_edit' mealplan.id %}">Edit</a>
      <a href="{% url 'mealplan_delete' mealplan.id %}">Delete</a>
    </div>
    <h1>{{ mealplan.name }}</h1>
    <p>
      Eat on {{ mealplan.date }} |
    </p>
    
    <h2>Recipes</h2>
    <p>
      {% for recipe in mealplan.recipes.all %}
        <li><a = href="{% url 'recipe_detail' recipe.id %}">{{ recipe.name }}</a></li>
      {% endfor %}
    </p>
  </main>
{% endblock content %}

mealplans/templates/mealplans/edit.html
{% extends 'base.html' %}

{% block content %}
  <main class="recipe-form">
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <div class="control">
        <button class="button">Update</button>
      </div>
    </form>
  </main>
{% endblock content %}

mealplans/templates/mealplans/list.html
{% extends 'base.html' %}

  {% block content %}
  <a href="{% url 'mealplan_new' %}">Create</a>
  <main class="recipe-grid">
    {% for mealplan in mealplan_list %}
    <div class="recipe-card">
      <h2 class="recipe-card-title">
        <a href="{% url 'mealplan_detail' mealplan.pk %}">{{ mealplan.name }}</a>
      </h2>
      <p class="recipe-card-date">{{ mealplan.updated }}</p>
    </div>
    {% endfor %}
  </main>
  {% endblock content %}


  {% block pagination %}
  <footer>
    <span>
      {% if page_obj.has_previous %}
        <a href="?page={{page_obj.previous_page_number }}">Previous</a>
      {% endif %}
      <span>
        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
      </span>
      {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">Next</a>
      {% endif %}
    </span>
  </footer>
  {% endblock pagination %}

mealplans/templates/mealplans/new.html
{% extends 'base.html' %}

{% block content %}
<main class="recipe-form">
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <div class="control">
        <button class="button">Create</button>
      </div>
    </form>
  </main>
{% endblock content %}